- name: app_deploy
  become: true
  gather_facts: No
  hosts: test_app

  tasks:
    - name: pip_is_installed
      package: 
        name: python-pip

    - name: install_libpq-dev
      apt:
        name: libpq-dev
        state: latest

    - name: install_python-dev
      apt:
        name: python-dev
        state: latest

    - pip:
        requirements: /var/www/html/requirements.txt
